### ISSUE TITLE
Error Download audio file on main thread

### ISSUE THREAD

**Issue by eslamfaisal** [bluefireteam/audioplayers#1062]
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(Unexpected error!, null, android.os.NetworkOnMainThreadException
E/flutter ( 9091): 	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1668)
E/flutter ( 9091): 	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:115)
E/flutter ( 9091): 	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
E/flutter ( 9091): 	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
E/flutter ( 9091): 	at com.android.okhttp.Dns$1.lookup(Dns.java:41)
E/flutter ( 9091): 	at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:178)
E/flutter ( 9091): 	at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:144)
E/flutter ( 9091): 	at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:86)
E/flutter ( 9091): 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:176)
E/flutter ( 9091): 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
E/flutter ( 9091): 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
E/flutter ( 9091): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
E/flutter ( 9091): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
E/flutter ( 9091): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
E/flutter ( 9091): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
E/flutter ( 9091): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:248)
E/flutter ( 9091): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
E/flutter ( 9091): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
E/flutter ( 9091): 	at java.net.URL.openStream(URL.java:1072)
E/flutter ( 9091): 	at xyz.luan.audioplayers.WrappedSoundPool.downloadUrl(WrappedSoundPool.kt:242)
E/flutter ( 9091): 	at xyz.luan.audioplayers.WrappedSoundPool.loadTempFileFromNetwork(WrappedSoundPool.kt:231)
E/flutter ( 9091): 	at xyz.luan.audioplayers.WrappedSoundPool.getAudioPath(WrappedSoundPool.kt:227)
E/flutter ( 9091): 	at xyz.luan.audioplayers.WrappedSoundPool.setUrl(WrappedSoundPool.kt:151)
E/flutter ( 9091): 	at xyz.luan.audioplayers.AudioplayersPlugin.handleMethodCall(AudioplayersPlugin.kt:59)
E/flutter ( 9091): 	at xyz.luan.audioplayers.AudioplayersPlugin.onMethodCall(AudioplayersPlugin.kt:33)
E/flutter ( 9091): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/flutter ( 9091): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:178)
E/flutter ( 9091): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$handleMessageFromDart$0$DartMessenger(DartMessenger.java:206)
E/flutter ( 9091): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$6ZD1MYkhaLxyPjtoFDxe45u43DI.run(Unknown Source:12)
E/flutter ( 9091): 	at android.os.Handler.handleCallback(Handler.java:938)
E/flutter ( 9091): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter ( 9091): 	at android.os.Looper.loopOnce(Looper.java:226)
E/flutter ( 9091): 	at android.os.Looper.loop(Looper.java:313)
E/flutter ( 9091): 	at android.app.ActivityThread.main(ActivityThread.java:8641)
E/flutter ( 9091): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 9091): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
E/flutter ( 9091): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
E/flutter ( 9091): , null)
E/flutter ( 9091): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter ( 9091): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
E/flutter ( 9091): <asynchronous suspension>
E/flutter ( 9091): #2      AudioPlayer.invokeMethod (package:audioplayers/src/audioplayer.dart:151:20)
E/flutter ( 9091): <asynchronous suspension>
E/flutter ( 9091): #3      AudioPlayer.play (package:audioplayers/src/audioplayer.dart:173:20)
E/flutter ( 9091): <asynchronous suspension>
E/flutter ( 9091): #4      QouranViewModel.playNextAya (package:aslehle/screens/qouran/viewmodel/qouran_view_model.dart:278:5)
E/flutter ( 9091): <asynchronous suspension>
E/flutter ( 9091):

**Comment by luanpotter** [comment]
Please follow the issue template, this issue is unreadable as is.
