### ISSUE TITLE
No enum constant xyz.luan.audioplayers.ReleaseMode.stop

### ISSUE THREAD

**Issue by tamoyal** [bluefireteam/audioplayers#1065]
There is something wrong about the way enums are handled on Android. My app started crashing after upgrading to the latest version.

The crash happens when I reference an enum like `ReleaseMode.stop` (`await _audioPlayer.setReleaseMode(ReleaseMode.stop);`). Below is the stack trace:

```
PlatformException (PlatformException(Unexpected error!, No enum constant xyz.luan.audioplayers.ReleaseMode.stop, java.lang.IllegalArgumentException: No enum constant xyz.luan.audioplayers.ReleaseMode.stop
	at java.lang.Enum.valueOf(Enum.java:257)
	at xyz.luan.audioplayers.ReleaseMode.valueOf(Unknown Source:7)
	at xyz.luan.audioplayers.AudioplayersPlugin.handleMethodCall(AudioplayersPlugin.kt:255)
	at xyz.luan.audioplayers.AudioplayersPlugin.onMethodCall(AudioplayersPlugin.kt:32)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7842)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
, null))
```

I'm on the latest - master (from my lock file):
```
  audioplayers:
    dependency: "direct main"
    description:
      path: "packages/audioplayers"
      ref: HEAD
      resolved-ref: "46816bf55859c9c88b204e3828cce6190ff87483"
      url: "https://github.com/bluefireteam/audioplayers"
```

**Comment by luanpotter** [comment]
This was fixed by https://github.com/bluefireteam/audioplayers/pull/1002/files
