### ISSUE TITLE
How to play audio files from assets on iOS?

### ISSUE THREAD

**Issue by aoatmon** [bluefireteam/audioplayers#1084]
**Full Description**

to play an audio file from asset I followed the approach below, but seems to be working only on android;
### 
**Expected behavior**

the app behavior is consistent across platforms

**Actual behavior**

works on Android, but on iOS throws as reported in `Log Errors`

**Code to Reproduce**

```dart
import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/services.dart';

abstract class AudioEffect {
  String get asset;
  AudioPlayer? _player;

  void dispose() => _player?.dispose();

  void play() async {
    _player ??= AudioPlayer();
    final bytes = await rootBundle.load(asset);
    await _player!.playBytes(bytes.buffer.asUint8List(
      bytes.offsetInBytes,
      bytes.lengthInBytes,
    ));
  }
}

```

**Log Errors**

```
An Observatory debugger and profiler on iPad Pro (12.9-inch) (5th generation) is available at: http://127.0.0.1:56082/6cmr154hNh0=/
The Flutter DevTools debugger and profiler on iPad Pro (12.9-inch) (5th generation) is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:56082/6cmr154hNh0=/
flutter: Error: message=runZonedGuarded error=PlatformException(Not supported, Only Android is currently supported, null, null) stacktrace=#0      AudioPlayer.playBytes (package:audioplayers/src/audioplayer.dart:208:7)
#1      AudioEffect.play (package:xxx/shared/audio/audio_effect.dart:16:35)
<asynchronous suspension>

```

**Platforms**

```
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.2.1 21D62 darwin-x64, locale en-EE)
    • Flutter version 2.10.3 at /Users/francesco/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (8 days ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/francesco/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.65.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (4 available)
    • Pixel 3a (mobile)                              • 965AY0WP5C                           • android-arm64  • Android 12 (API 31)
    • iPad Pro (12.9-inch) (5th generation) (mobile) • 640922FD-0A01-42A4-A5FD-94704A538EF2 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)                                • macos                                • darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)                                   • chrome                               • web-javascript • Google Chrome 99.0.4844.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by dmendoza05** [comment]
Have you tried using AudioCache?

```In order to play Local Assets, you must use the AudioCache class. AudioCache is not available for Flutter Web.``` - per documentation.

**Comment by luanpotter** [comment]
`playBytes` is not available for iOS. Please check the [feature parity table](https://github.com/bluefireteam/audioplayers/blob/main/feature_parity_table.md) for details.

That does not mean at all you can't play assets, you just need to use `AudioCache` (on v0), or, on (v1), `player.setSource(AssetSource('path'))`.
