### ISSUE TITLE
Unable to play audio file from asset and getting MissingPluginException error

### ISSUE THREAD

**Issue by KayAay94** [bluefireteam/audioplayers#1104]
I'm trying to play audio file from asset in Flutter windows application, but it is giving the MissingPluginException error

I have created a directory named assets and place .mp3 file in that directory
This is my code snippet:
``` AudioPlayer audioPlayer = AudioPlayer();
  AudioCache audioCache = AudioCache();

playSound()
{
    audioCache.play('tone.mp3', isNotification: true);
}
```
This is my pubspec.yaml file code:
```  assets:
    - img/
    - assets/tone.mp3
 ```

On execution of this code the following exception appears:
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method play on channel xyz.luan/audioplayers)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
<asynchronous suspension>
#1      AudioPlayer.invokeMethod (package:audioplayers/src/audioplayer.dart:151:20)
<asynchronous suspension>
#2      AudioPlayer.play (package:audioplayers/src/audioplayer.dart:173:20)
<asynchronous suspension>
#3      AudioCache.play (package:audioplayers/src/audio_cache.dart:164:5)
<asynchronous suspension>
```
flutter doctor output is:
```
D:\Code\test>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.2, on Microsoft Windows [Version 10.0.19044.1645], locale en-PK)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.9)
[√] Android Studio (version 2020.3)
[√] Connected device (3 available)
[√] HTTP Host Availability

• No issues found!
```
I don't get the reason of this error. In the main features table of documentation, it shows support for windows. 
Please help me to solve this issue.

**Comment by mkay-42069** [comment]
Guessing you're still on 0.20.1, which doesn't support Windows.

v1 hasn't officially landed yet, but can be used by adding `audioplayers: ^1.0.0-rc.1`

**Comment by KayAay94** [comment]
Thanks alot. It workedd
