### ISSUE TITLE
bug: [android] getDuration causes MEDIA_ERROR_UNKNOWN 

### ISSUE THREAD

**Issue by Gustl22** [bluefireteam/audioplayers#1137]
Calling getDuration instantly after loading source causes MEDIA_ERROR_UNKNOWN

See logs: https://github.com/bluefireteam/audioplayers/runs/6538159265

**Code to Reproduce**
See executing integration tests on android:
https://github.com/bluefireteam/audioplayers/pull/1128

**Log Errors**
```
Attempt to call getDuration in wrong state: mPlayer=0x787da258ce90, mCurrentState=4
E/MediaPlayerNative(12460): error (-38, 0)
E/MediaPlayer(12460): Error (-38,0)
E/flutter (12460): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: MediaPlayer error with what:MEDIA_ERROR_UNKNOWN {what:-38} extra:MEDIA_ERROR_UNKNOWN {extra:0}
E/flutter (12460): #0      MethodChannelAudioplayersPlatform._doHandlePlatformCall (package:audioplayers_platform_interface/method_channel_audioplayers_platform.dart:175:9)
E/flutter (12460): #1      MethodChannelAudioplayersPlatform.platformCallHandler (package:audioplayers_platform_interface/method_channel_audioplayers_platform.dart:148:7)
E/flutter (12460): #2      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:404:55)
E/flutter (12460): #3      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:397:34)
E/flutter (12460): #4      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:380:35)
E/flutter (12460): #5      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:377:46)
E/flutter (12460): #6      _invoke2.<anonymous closure> (dart:ui/hooks.dart:190:15)
E/flutter (12460): #7      _rootRun (dart:async/zone.dart:1426:13)
E/flutter (12460): #8      _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter (12460): #9      _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter (12460): #10     _invoke2 (dart:ui/hooks.dart:189:10)
E/flutter (12460): #11     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
E/flutter (12460): #12     _Channel.push (dart:ui/channel_buffers.dart:132:31)
E/flutter (12460): #13     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
E/flutter (12460): #14     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:589:22)
E/flutter (12460): #15     _dispatchPlatformMessage (dart:ui/hooks.dart:89:31)
E/flutter (12460): 
```

**Platforms**
- Android

* OS: android
* OS version: system-images;android-30;google_apis;x86
* Device: emulator
* flutter version: 3.0.0
* audioplayers version: master
* release or not release: test

**Comment by Usama-Ishfaq101** [comment]
Is there any update on this issue as I'm facing the same issue, can be produced at multiple situations. If open player and navigate back before player is initialized fetching complete stream produces same error, play then pause/stop before all stream content is fetched produces same issue.

**Comment by Usama-Ishfaq101** [comment]
Thanks, it did resolved the error in one place which is when playing/pausing before buffering. But it is still occur in below scenario,
If you navigate to audio page and click on play button, audio will start to  buffer, if you navigate back audio player to previous page before audio file is fetched, it throws exception. This is not much a problem but it happens.

**Comment by Gustl22** [comment]
@Usama-Ishfaq101 can you raise a new issue, if it still occurs, with as much detail as needed?
