### ISSUE TITLE
does not work on flutter-pi 

### ISSUE THREAD

**Issue by BigGitWorld** [bluefireteam/audioplayers#1154]
Hi!
I'm using the ``[1.0.0-rc.4](https://pub.dev/packages/audioplayers/versions/1.0.0-rc.4)`` that works fine in an Linux ubuntu desktop.
but when I use it in a flutter-pi project, it shows me the below error:

```
[compositor] Preferred framebuffer depth for hardware cursor is not supported by flutter-pi.
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method setSourceUrl on channel xyz.luan/audioplayers)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
<asynchronous suspension>
#1      AudioPlayer.play (package:audioplayers/src/audioplayer.dart:112:5)
<asynchronous suspension>
```
Do I have to do something to work in raspberrypi by flutter-pi?
Note: sound is enabled in my raspberry pi.

**Comment by luanpotter** [comment]
> No implementation found for method setSourceUrl

That is very interesting, it appears Flutter is not recognizing your flutter-pi as "linux" in order for audioplayers to use the correct binding.
Could you please try using any other flutter dependencies with native linux code?
I wonder if this is an issue with Flutter itself.

**Comment by BigGitWorld** [comment]
> That is very interesting, it appears Flutter is not recognizing your flutter-pi as "linux" in order for audioplayers to use the correct binding. 

But why this has to be happened?


> Could you please try using any other flutter dependencies with native linux code? I wonder if this is an issue with Flutter itself.

What do you mean exactly? Do you mean I use ``audioplayers_linux`` package directly in my project? or use another flutter package with a native linux code?
if the second is right, I'm using other packages such as ``flutter_libserialport`` in my flutter-pi project and it is working fine.

**Comment by luanpotter** [comment]
> or use another flutter package with a native linux code

yes that is what I meant. interesting, I don't understand why `flutter_libserialport` works and AP doesn't. I compared our configurations for the linux binding; the only difference is that libserialport does not use federation and we do. But that should not affect anything.

I just tried running our example (`packages/audioplayers/example`) on my Arch Linux and it worked. Could you please try clonning the repo and running that on your raspberry pi? I wonder if something else is causing interference.

**Comment by HSVDO** [comment]
Hey, I ran into a similar issue using flutter-pi and audioplayers package.

- Flutter 3.19.5 stable
- audioplayers: ^4.0.0, ^5.0.0 and ^6.0.0
- Raspberry Pi 3B with [flutter-pi](https://github.com/ardera/flutter-pi)
- Raspbian 11 (Bullseye)

I tried my own code - running on all platforms except Linux using flutter-pi pretty fine - and I also deployed the `audioplayers/example` project using flutter-pi. The example's UI works properly, when pressing the play button the same error is thrown:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method create on channel xyz.luan/audioplayers)
#0   MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332) <asynchronous suspension>
#1   AudioplayersPlatform.create (package:audioplayers_platform_interfaces/src/audioplayers_platform.dart:18) <asynchronous suspension>
#2   AudioPlayer._create (package:audioplayers/src/audioplayer.dart:175) <asynchronous suspension>
```

In addition I checked the platform detected by flutter. The result is 'linux'.

While writing this comment, I found [this issue in the flutter-pi repo](https://github.com/ardera/flutter-pi/issues/408) which might explain the problems. I will try to understand what's happening there in the next days. But as I am new to the platform channel mechanic I can't promise any valuable results 😄
