### ISSUE TITLE
Crash when call method play in second time.

### ISSUE THREAD

**Issue by haiquang9994** [bluefireteam/audioplayers#1160]
Crash when call method play in second time.

**Full Description**
I'm building an app, when passing in a list of sentences, the app will read each sentence in turn. I use method player.play(DeviceFileSource(path)). The first sentence is work. but when going to the second sentence, the app crashes.

**Log Errors**
```
Exception has occurred.
PlatformException (PlatformException(Unexpected error!, null, java.lang.IllegalStateException
	at android.media.MediaPlayer._setDataSource(Native Method)
	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1275)
	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1258)
	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1215)
	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1192)
	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1157)
	at xyz.luan.audioplayers.source.UrlSource.setForMediaPlayer(UrlSource.kt:16)
	at xyz.luan.audioplayers.player.MediaPlayerPlayer.setSource(MediaPlayerPlayer.kt:51)
	at xyz.luan.audioplayers.player.WrappedPlayer.setSource(WrappedPlayer.kt:29)
	at xyz.luan.audioplayers.AudioplayersPlugin.handler(AudioplayersPlugin.kt:87)
	at xyz.luan.audioplayers.AudioplayersPlugin.access$handler(AudioplayersPlugin.kt:23)
	at xyz.luan.audioplayers.AudioplayersPlugin$onAttachedToEngine$1$1.invoke(AudioplayersPlugin.kt:39)
	at xyz.luan.audioplayers.AudioplayersPlugin$onAttachedToEngine$1$1.invoke(AudioplayersPlugin.kt:39)
	at xyz.luan.audioplayers.AudioplayersPlugin$safeCall$1.invokeSuspend(AudioplayersPlugin.kt:58)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
, null))
```

**Screenshots**
<img width="935" alt="Screen Shot 2022-06-13 at 16 32 15" src="https://user-images.githubusercontent.com/13959257/173324422-28062a37-1ac7-47b5-b602-951fdd2d2001.png">

**Platforms**
* OS: android
* Device: oneplus 6
* flutter version: 3.0.2
* audioplayers version: 1.0

**Comment by miphik** [comment]
+1

**Comment by g5applicationdev** [comment]
+1

**Comment by XMitja** [comment]
I noticed it failed with the example app too when switching between laser and nasa sources, I made a one-line fix by calling reset before setting source:
#1169

**Comment by alperenekin** [comment]
+1

**Comment by lidaweicn** [comment]
+1

**Comment by lidaweicn** [comment]
```
await player.stop();
```
if playing

**Comment by spydon** [comment]
Is this still an issue in audioplayers 1.0.1?

**Comment by Gustl22** [comment]
You can also test now with `audioplayers: ^1.1.0`
