### ISSUE TITLE
Verify gstreamer installation in linux

### ISSUE THREAD

**Issue by TaylorHo** [bluefireteam/audioplayers#1178]
**Short Description**
If the gstreamer isn't installed in Linux, it throws an error. Is there a **way to verify if the package is installed**, and **show a warning explaining that the gstreamer is necessary** (if not installed), instead of crashing the app run?
&nbsp;

**Full Description**
The error thrown when the gstreamer isn't installed is the following one (short version):
```
CMake Error at /usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:463 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:643 (_pkg_check_modules_internal)
  flutter/ephemeral/.plugin_symlinks/audioplayers_linux/linux/CMakeLists.txt:25 (pkg_check_modules)
```

<details>
  <summary>Show the full output (result of <code>flutter run -v</code>)</summary>
  <br/>
  
```
[  +55 ms] executing: uname -m
[  +25 ms] Exit code 0 from: uname -m
[   +1 ms] x86_64
[   +4 ms] executing: [/home/taylorho/src/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +5 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 4f034a40454b86064fdcb9dce156975c3fad0572
[        ] executing: [/home/taylorho/src/flutter/] git tag --points-at 4f034a40454b86064fdcb9dce156975c3fad0572
[  +12 ms] Exit code 0 from: git tag --points-at 4f034a40454b86064fdcb9dce156975c3fad0572
[   +1 ms] executing: [/home/taylorho/src/flutter/] git describe --match *.*.* --long --tags 4f034a40454b86064fdcb9dce156975c3fad0572
[  +46 ms] Exit code 0 from: git describe --match *.*.* --long --tags 4f034a40454b86064fdcb9dce156975c3fad0572
[        ] 3.0.0-0.0.pre-1312-g4f034a4045
[  +40 ms] executing: [/home/taylorho/src/flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] origin/master
[        ] executing: [/home/taylorho/src/flutter/] git ls-remote --get-url origin
[   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +36 ms] executing: [/home/taylorho/src/flutter/] git rev-parse --abbrev-ref HEAD
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +41 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +44 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +71 ms] Skipping pub get: version match.
[  +23 ms] Found plugin audioplayers at /home/taylorho/.pub-cache/hosted/pub.dartlang.org/audioplayers-1.0.0/
[   +3 ms] Found plugin audioplayers_android at /home/taylorho/.pub-cache/hosted/pub.dartlang.org/audioplayers_android-1.0.0/
[   +1 ms] Found plugin audioplayers_darwin at /home/taylorho/.pub-cache/hosted/pub.dartlang.org/audioplayers_darwin-1.0.0/
[   +2 ms] Found plugin audioplayers_linux at /home/taylorho/.pub-cache/hosted/pub.dartlang.org/audioplayers_linux-1.0.0/
[   +2 ms] Found plugin audioplayers_web at /home/taylorho/.pub-cache/hosted/pub.dartlang.org/audioplayers_web-1.0.0/
[   +1 ms] Found plugin audioplayers_windows at /home/taylorho/.pub-cache/hosted/pub.dartlang.org/audioplayers_windows-1.0.0/
[  +19 ms] Found plugin path_provider at /home/taylorho/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.11/
[   +1 ms] Found plugin path_provider_android at /home/taylorho/.pub-cache/hosted/pub.dartlang.org/path_provider_android-2.0.15/
[   +2 ms] Found plugin path_provider_ios at /home/taylorho/.pub-cache/hosted/pub.dartlang.org/path_provider_ios-2.0.10/
[   +1 ms] Found plugin path_provider_linux at /home/taylorho/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.1.7/
[   +1 ms] Found plugin path_provider_macos at /home/taylorho/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-2.0.6/
[   +1 ms] Found plugin path_provider_windows at /home/taylorho/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.1.0/
[  +41 ms] Found plugin audioplayers at /home/taylorho/.pub-cache/hosted/pub.dartlang.org/audioplayers-1.0.0/
[   +1 ms] Found plugin audioplayers_android at /home/taylorho/.pub-cache/hosted/pub.dartlang.org/audioplayers_android-1.0.0/
[   +1 ms] Found plugin audioplayers_darwin at /home/taylorho/.pub-cache/hosted/pub.dartlang.org/audioplayers_darwin-1.0.0/
[   +1 ms] Found plugin audioplayers_linux at /home/taylorho/.pub-cache/hosted/pub.dartlang.org/audioplayers_linux-1.0.0/
[   +1 ms] Found plugin audioplayers_web at /home/taylorho/.pub-cache/hosted/pub.dartlang.org/audioplayers_web-1.0.0/
[   +1 ms] Found plugin audioplayers_windows at /home/taylorho/.pub-cache/hosted/pub.dartlang.org/audioplayers_windows-1.0.0/
[  +12 ms] Found plugin path_provider at /home/taylorho/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.11/
[        ] Found plugin path_provider_android at /home/taylorho/.pub-cache/hosted/pub.dartlang.org/path_provider_android-2.0.15/
[   +1 ms] Found plugin path_provider_ios at /home/taylorho/.pub-cache/hosted/pub.dartlang.org/path_provider_ios-2.0.10/
[        ] Found plugin path_provider_linux at /home/taylorho/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.1.7/
[        ] Found plugin path_provider_macos at /home/taylorho/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-2.0.6/
[   +1 ms] Found plugin path_provider_windows at /home/taylorho/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.1.0/
[  +56 ms] Generating /home/taylorho/projetos/reader_kitty/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +81 ms] Initializing file store
[   +8 ms] Skipping target: gen_localizations
[   +4 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents:
/home/taylorho/projetos/reader_kitty/.dart_tool/package_config_subset,/home/taylorho/projetos/reader_kitty/.dart_tool/flutter_build/dart_plugin_regist
rant.dart}
[  +11 ms] Found plugin audioplayers at /home/taylorho/.pub-cache/hosted/pub.dartlang.org/audioplayers-1.0.0/
[        ] Found plugin audioplayers_android at /home/taylorho/.pub-cache/hosted/pub.dartlang.org/audioplayers_android-1.0.0/
[        ] Found plugin audioplayers_darwin at /home/taylorho/.pub-cache/hosted/pub.dartlang.org/audioplayers_darwin-1.0.0/
[        ] Found plugin audioplayers_linux at /home/taylorho/.pub-cache/hosted/pub.dartlang.org/audioplayers_linux-1.0.0/
[        ] Found plugin audioplayers_web at /home/taylorho/.pub-cache/hosted/pub.dartlang.org/audioplayers_web-1.0.0/
[        ] Found plugin audioplayers_windows at /home/taylorho/.pub-cache/hosted/pub.dartlang.org/audioplayers_windows-1.0.0/
[   +6 ms] Found plugin path_provider at /home/taylorho/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.11/
[        ] Found plugin path_provider_android at /home/taylorho/.pub-cache/hosted/pub.dartlang.org/path_provider_android-2.0.15/
[        ] Found plugin path_provider_ios at /home/taylorho/.pub-cache/hosted/pub.dartlang.org/path_provider_ios-2.0.10/
[        ] Found plugin path_provider_linux at /home/taylorho/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.1.7/
[        ] Found plugin path_provider_macos at /home/taylorho/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-2.0.6/
[        ] Found plugin path_provider_windows at /home/taylorho/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.1.0/
[  +10 ms] gen_dart_plugin_registrant: Complete
[        ] Skipping target: _composite
[   +1 ms] complete
[   +4 ms] Launching lib/main.dart on Linux in debug mode...
[   +3 ms] /home/taylorho/src/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/taylorho/src/flutter/bin/cache/dart-sdk/bin/snapshots/frontend_server.dart.snapshot --sdk-root
/home/taylorho/src/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names
--experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill /tmp/flutter_tools.SABISL/flutter_tool.ECGCLF/app.dill --packages
/home/taylorho/projetos/reader_kitty/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts
--track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build/c075001b96339384a97db4862b8ab8db.cache.dill.track.dill
--source /home/taylorho/projetos/reader_kitty/.dart_tool/flutter_build/dart_plugin_registrant.dart --source
package:flutter/src/dart_plugin_registrant.dart
-Dflutter.dart_plugin_registrant=file:///home/taylorho/projetos/reader_kitty/.dart_tool/flutter_build/dart_plugin_registrant.dart --verbosity=error
--flutter-widget-cache --enable-experiment=alternative-invalidation-strategy
[  +21 ms] Building Linux application...
[  +17 ms] <- compile package:reader_kitty/main.dart
[   +1 ms] executing: [build/linux/x64/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DFLUTTER_TARGET_PLATFORM=linux-x64
/home/taylorho/projetos/reader_kitty/linux
[  +38 ms] -- Checking for module 'gstreamer-1.0'
[        ] --   No package 'gstreamer-1.0' found
[        ] -- Configuring incomplete, errors occurred!
[        ] See also "/home/taylorho/projetos/reader_kitty/build/linux/x64/debug/CMakeFiles/CMakeOutput.log".
[        ] CMake Error at /usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:463 (message):
[   +1 ms]   A required package was not found
[        ] Call Stack (most recent call first):
[        ]   /usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:643 (_pkg_check_modules_internal)
[        ]   flutter/ephemeral/.plugin_symlinks/audioplayers_linux/linux/CMakeLists.txt:25 (pkg_check_modules)
[  +16 ms] Building Linux application... (completed in 68ms)
[+9857 ms] Exception: Unable to generate build files
[   +2 ms] "flutter run" took 10,427ms.
[   +4 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:707:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1195:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[  +80 ms] ensureAnalyticsSent: 79ms
[        ] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

</details>

The feature request is to **create a way to verify if the package is installed**. If not installed, show a warning explaining that the package needs to be installed (it's better than just crashing the application since the users that don't have such deep knowledge wouldn't know which package isn't installed with the default error message).
&nbsp;

**Platforms**
This feature is just useful for Linux users.
&nbsp;

**Sample Files/URLs/Sources**
The error message, explaining that the package needs to be installed (if isn't yet), could have a link to the gstreamer installation guide:
- [gstreamer installation guide](https://gstreamer.freedesktop.org/documentation/installing/on-linux.html?gi-language=c#install-gstreamer-on-ubuntu-or-debian)
&nbsp;

**Finally**
This feature would be useful for the newcomers to flutter, but idk if it's possible to be implemented. Btw, thanks for listening.

**Comment by Gustl22** [comment]
I think it's hard to implement. Maybe we should add it to the README next to Getting started. 
Currently there's a note in [Troubleshooting](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md#linux-build-requirements)

**Comment by TaylorHo** [comment]
Oh, Ok! I've seen the PR doing the changes.
Thanks!
