### ISSUE TITLE
[iOS] [Real Device] Error occurs when sound is played continuously.

### ISSUE THREAD

**Issue by hukusuke1007** [bluefireteam/audioplayers#1204]
**Full Description**
At first the sound sounds fine, but after a few taps the sound stops. At that time an error occurs.

No errors occur in the simulator. However, errors do occur on the real device.

Is there any way to solve this problem?

**Code to Reproduce**

```dart
  GestureDetector(
    child: Text('Press'),
    onTap: () async {
      for (var i = 0; i < 100; i++) {
        print(i);
        final player = AudioPlayer();
        await player.play(AssetSource('audio/handclap1.mp3'));
        await Future<void>.delayed(const Duration(milliseconds: 100));
      }
    },
  ),
```

**Log Errors**
```log
flutter: 0
"method: setSourceUrl"
"playerId: f0ffb3ca-4f07-4971-86b4-602d08c33c7b"
""
"method: resume"

...

flutter: 52
"method: setSourceUrl"
"playerId: dfa54159-ec71-446b-a42b-17b003d09506"
""
[VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: AVPlayerItem.Status.failed
#0      MethodChannelAudioplayersPlatform._doHandlePlatformCall (package:audioplayers_platform_interface/method_channel_audioplayers_platform.dart:173:9)
#1      MethodChannelAudioplayersPlatform.platformCallHandler (package:audioplayers_platform_interface/method_channel_audioplayers_platform.dart:147:7)
#2      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:404:55)
#3      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:397:34)
#4      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:380:35)
#5      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:377:46)
#6      _invoke2.<anonymous closure> (dart:ui/hooks.dart:190:15)
#7      _rootRun (dart:async/zone.dart:1426:13)
#8      _CustomZone.run (dart:async/zone.dart:1328:19)
#9      _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#10     _invoke2 (dart:ui/hooks.dart:189:10)
#11     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#12     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#13     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#14     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:589:22)
#15     _dispatchPlatformMessage (dart:ui/hooks.dart:89:31)
```

**Files/URLs/Sources**
local mp3 file.

**Screenshots**
No

**Platforms**
* OS: ios 
* OS version: 15.5
* Device: iPhone SE3. Real Device.
* audioplayers version: 1.0.1

**Comment by S-Man42** [comment]
Same exception here!

My files are wav or mp3, temporary created `File` objects.

**Comment by hukusuke1007** [comment]
Use soundpool instead of this plugin. This plugin worked fine.
https://pub.dev/packages/soundpool
