### ISSUE TITLE
PlatformException: Unexpected error!

### ISSUE THREAD

**Issue by mdddj** [bluefireteam/audioplayers#1218]
```dart



Flutter Exception

PlatformException(Unexpected error!, null, java.lang.IllegalStateException at android.media.MediaPlayer._stop(Native Method) at android.media.MediaPlayer.stop(MediaPlayer.java:1357) 
at j7.i.stop(Unknown Source:2)
at j7.m.A(Unknown Source:18) 
at i7.d.n(Unknown Source:183) 
at i7.d.d(Unknown Source:0) 
at i7.d$c.b(Unknown Source:14) 
at i7.d$c.invoke(Unknown Source:4) 
at i7.d$e.invokeSuspend(Unknown Source:16) 

at kotlin.coroutines.jvm.internal.a.resumeWith(Unknown Source:11) 
at x5.p0.run(Unknown Source:88) 
at kotlinx.coroutines.internal.l.run(Unknown Source:12) 
at kotlinx.coroutines.scheduling.k.run(Unknown Source:2) 
at kotlinx.coroutines.scheduling.a.B(Unknown Source:0) 
at kotlinx.coroutines.scheduling.a$c.d(Unknown Source:14) 
at kotlinx.coroutines.scheduling.a$c.n(Unknown Source:28) 
at kotlinx.coroutines.scheduling.a$c.run(Unknown Source:0) , null)

1
#0 StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607)
2
#1 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167)
3
<asynchronous suspension>
4
#2 AudioPlayer.release (package:audioplayers/src/audioplayer.dart:153)
5
<asynchronous suspension>
```

flutter doctor
```dart
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm (Rosetta),
    locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.2)
[✓] VS Code (version 1.69.1)
[✓] Proxy Configuration
[✓] Connected device (4 available)
```

**Comment by Gustl22** [comment]
Plz use issue template!
