### ISSUE TITLE
Audiocache: Unhandled Exception: Unable to load asset

### ISSUE THREAD

**Issue by guivr** [bluefireteam/audioplayers#1279]
## Checklist
- [x] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [x] I made sure that the issue I am raising doesn't already exist

I'm trying to load a file that was saved by the package `sound_recorder` inside `getApplicationDocumentsDirectory()`, however, `AudioCache` is unable to load the file on Android (works on iOS).

The file exists, I've checked with .existsSync().

If I use Audioplayer.play() instead, it loads the audio. But using `AudioCache` `.load` will return the error:

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Unable to load asset: /data/user/0/com.example.funny_voice_changer/app_flutter/audio.aac
E/flutter ( 8870): #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:237:7)
E/flutter ( 8870): <asynchronous suspension>
E/flutter ( 8870): #1      AudioCache.fetchToMemory (package:audioplayers/src/audio_cache.dart:89:22)
E/flutter ( 8870): <asynchronous suspension>
E/flutter ( 8870): #2      AudioCache.load (package:audioplayers/src/audio_cache.dart:115:31)
E/flutter ( 8870): <asynchronous suspension>
E/flutter ( 8870): #3      _MyHomePageState.setAudio (package:funny_voice_changer/main.dart:159:17)
E/flutter ( 8870): <asynchronous suspension>
E/flutter ( 8870): 
```

**Comment by Gustl22** [comment]
Can't you just use [DeviceFileSource](https://github.com/bluefireteam/audioplayers/blob/main/getting_started.md#sources) without using AudioCache?

**Comment by guivr** [comment]
I can't, because I'm using AudioCache to fix another issue (#1225)

**Comment by vishalpatel1327** [comment]
same issue. i cant load mp3 file from assets folder

`E/flutter ( 5794): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Unable to load asset: assets/audio/beep.mp3
E/flutter ( 5794): #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:258:7)
E/flutter ( 5794): <asynchronous suspension>
E/flutter ( 5794): #1      AudioCache.fetchToMemory (package:audioplayers/src/audio_cache.dart:75:22)
E/flutter ( 5794): <asynchronous suspension>
E/flutter ( 5794): #2      AudioCache.load (package:audioplayers/src/audio_cache.dart:101:31)
E/flutter ( 5794): <asynchronous suspension>
E/flutter ( 5794): #3      AudioPlayer.setSourceAsset (package:audioplayers/src/audioplayer.dart:237:17)
E/flutter ( 5794): <asynchronous suspension>
E/flutter ( 5794): #4      _HomeScreenState.build.<anonymous closure> (package:flutter_chemist/screen/home/home_screen.dart:76:13)
E/flutter ( 5794): <asynchronous suspension>`

**Comment by guivr** [comment]
Sorry, is there any workaround to fix this issue? :(
Can't launch my app for Android only because of this

**Comment by Nassimboud** [comment]
AudioCache is dead, long live Sources
One of the main changes was my desire to "kill" the AudioCache API due to the vast confusion that it caused with users (despite our best efforts documenting everything).

We still have the AudioCache class but its APIs are exclusively dedicated to transforming asset files into local files, cache them, and provide the path. It however doesn't normally need be used by end users because the AudioPlayer itself is now capable of playing audio from any Source.

What is a Source? It's a sealed class that can be one of:

UrlSource: get the audio from a remote URL from the Internet
DeviceFileSource: access a file in the user's device, probably selected by a file picker
AssetSource: play an asset bundled with your app, normally within the assets directory
BytesSource (only some platforms): pass in the bytes of your audio directly (read it from anywhere).
If you use AssetSource, the AudioPlayer will use its instance of AudioCache (which defaults to the global cache if unchanged) automatically. This unifies all playing APIs under AudioPlayer and entirely removes the AudioCache detail for most users.

**Comment by guivr** [comment]
> AudioCache is dead, long live Sources One of the main changes was my desire to "kill" the AudioCache API due to the vast confusion that it caused with users (despite our best efforts documenting everything).
> 
> We still have the AudioCache class but its APIs are exclusively dedicated to transforming asset files into local files, cache them, and provide the path. It however doesn't normally need be used by end users because the AudioPlayer itself is now capable of playing audio from any Source.
> 
> What is a Source? It's a sealed class that can be one of:
> 
> UrlSource: get the audio from a remote URL from the Internet DeviceFileSource: access a file in the user's device, probably selected by a file picker AssetSource: play an asset bundled with your app, normally within the assets directory BytesSource (only some platforms): pass in the bytes of your audio directly (read it from anywhere). If you use AssetSource, the AudioPlayer will use its instance of AudioCache (which defaults to the global cache if unchanged) automatically. This unifies all playing APIs under AudioPlayer and entirely removes the AudioCache detail for most users.

`DeviceFileSource` won't work if the file is under the same name - unless there was an update. See #1225

**Comment by khoulyy** [comment]
Any updates?
