### ISSUE TITLE
Unexpected error! when playing audio file using DeviceFileSource on Android

### ISSUE THREAD

**Issue by RishiKar** [bluefireteam/audioplayers#1300]
## Checklist
- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

1. I am unable to play audio files that are recorded and stored in the device local storage using DeviceFileSource on Android without re-running the app.
2. I am able to play audio files from assets on the same device & emulator. 
3. I have no problems in iOS. Both playing from assets and playing using DeviceFileSource works
 
## Current bug behaviour

I can confirm the file exists
`/data/user/0/com.example.exampleApp/app_flutter/None.aac`
I can confirm that the code translates to
`audioPlayer.play(DeviceFileSource(audioFilePath))`
where audioFilePath is the file location mentioned above
I get an error.
If I close and restart the app and then try to play the saved file, it plays.

## Expected behaviour
Play file using DeviceFileSource on Android after recording it without having to close and restart the app

## Steps to reproduce
1. Record an audio file and store it in local storage
2. Play the file in next screen using DeviceFileSource
3. Receive error. Save the file . Close & Flutter Run the app
4. Play the saved file - It will play  
<details>
<summary>Code sample</summary>

```dart
void main() {
}
```

</details>

## Logs

```
E/MediaPlayerNative(27137): error (1, -2147483648)
D/AudioPlayers(27137): Unexpected error!
D/AudioPlayers(27137): java.io.IOException: Prepare failed.: status=0x1
D/AudioPlayers(27137): 	at android.media.MediaPlayer._prepare(Native Method)
D/AudioPlayers(27137): 	at android.media.MediaPlayer.prepare(MediaPlayer.java:1300)
D/AudioPlayers(27137): 	at xyz.luan.audioplayers.player.MediaPlayerPlayer.prepare(MediaPlayerPlayer.kt:89)
D/AudioPlayers(27137): 	at xyz.luan.audioplayers.player.WrappedPlayer.configAndPrepare(WrappedPlayer.kt:310)
D/AudioPlayers(27137): 	at xyz.luan.audioplayers.player.WrappedPlayer.setSource(WrappedPlayer.kt:31)
D/AudioPlayers(27137): 	at xyz.luan.audioplayers.AudioplayersPlugin.handler(AudioplayersPlugin.kt:91)
D/AudioPlayers(27137): 	at xyz.luan.audioplayers.AudioplayersPlugin.access$handler(AudioplayersPlugin.kt:25)
D/AudioPlayers(27137): 	at xyz.luan.audioplayers.AudioplayersPlugin$onAttachedToEngine$1$1.invoke(AudioplayersPlugin.kt:41)
D/AudioPlayers(27137): 	at xyz.luan.audioplayers.AudioplayersPlugin$onAttachedToEngine$1$1.invoke(AudioplayersPlugin.kt:41)
D/AudioPlayers(27137): 	at xyz.luan.audioplayers.AudioplayersPlugin$safeCall$1.invokeSuspend(AudioplayersPlugin.kt:62)
D/AudioPlayers(27137): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
D/AudioPlayers(27137): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
D/AudioPlayers(27137): 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
D/AudioPlayers(27137): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
D/AudioPlayers(27137): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
D/AudioPlayers(27137): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
D/AudioPlayers(27137): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
D/AudioPlayers(27137): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
E/flutter (27137): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(Unexpected error!, Prepare failed.: status=0x1, java.io.IOException: Prepare failed.: status=0x1
E/flutter (27137): 	at android.media.MediaPlayer._prepare(Native Method)
E/flutter (27137): 	at android.media.MediaPlayer.prepare(MediaPlayer.java:1300)
E/flutter (27137): 	at xyz.luan.audioplayers.player.MediaPlayerPlayer.prepare(MediaPlayerPlayer.kt:89)
E/flutter (27137): 	at xyz.luan.audioplayers.player.WrappedPlayer.configAndPrepare(WrappedPlayer.kt:310)
E/flutter (27137): 	at xyz.luan.audioplayers.player.WrappedPlayer.setSource(WrappedPlayer.kt:31)
E/flutter (27137): 	at xyz.luan.audioplayers.AudioplayersPlugin.handler(AudioplayersPlugin.kt:91)
E/flutter (27137): 	at xyz.luan.audioplayers.AudioplayersPlugin.access$handler(AudioplayersPlugin.kt:25)
E/flutter (27137): 	at xyz.luan.audioplayers.AudioplayersPlugin$onAttachedToEngine$1$1.invoke(AudioplayersPlugin.kt:41)
E/flutter (27137): 	at xyz.luan.audioplayers.AudioplayersPlugin$onAttachedToEngine$1$1.invoke(AudioplayersPlugin.kt:41)
E/flutter (27137): 	at xyz.luan.audioplayers.AudioplayersPlugin$safeCall$1.invokeSuspend(AudioplayersPlugin.kt:62)
E/flutter (27137): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/flutter (27137): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
E/flutter (27137): 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
E/flutter (27137): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
E/flutter (27137): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
E/flutter (27137): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
E/flutter (27137): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
E/flutter (27137): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
E/flutter (27137): , null)
E/flutter (27137): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter (27137): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
E/flutter (27137): <asynchronous suspension>
E/flutter (27137): #2      AudioPlayer.play (package:audioplayers/src/audioplayer.dart:123:5)
E/flutter (27137): <asynchronous suspension>
E/flutter (27137): #3      AudioPlayerService.playAudio (package:sixthousandthoughts/services/audioplayer_service.dart:108:5)
E/flutter (27137): <asynchronous suspension>
E/flutter (27137): #4      _TranscriptState.build.<anonymous closure> (package:sixthousandthoughts/screens/transcript.dart:544:33)
E/flutter (27137): <asynchronous suspension>
```

  Flutter doctor:
  ```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm, locale en-DE)
    • Flutter version 3.0.5 at /Users/rishikar/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (3 months ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/rishikar/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio 2.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.57.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • ONEPLUS A5010 (mobile)      • 657e6cf6      • android-arm64 • Android 10 (API 29)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64 • Android 13 (API 33) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64  • macOS 12.4 21F79 darwin-arm

[✓] HTTP Host Availability
    • All required HTTP hosts are available


  ```
</details>

## Environment information

* audioplayers version: 1.1.1

Platform 1: 
* OS name and version: 
* Device: 

* build mode: `debug`

* error peculiarities (optional):  The same file plays when the app is run again. There is no such issue on iOS app.

Platforms tested without any issue (optional): 
* test peculiarities:

**Comment by RishiKar** [comment]
Hi, I did some more testing as well as tried the solutions of using `mode: Playermode.mediaPlayer` but to no avail.
I tried changing name to small case - did not work
I tried rolling back to 1.0.0 but does not work
I also tried to check whether any async function is not being awaited for - looks all good

The behaviour is baffling as the app on being closed and restarted plays the same file flawlessly, with pause/resume/seek all working as they should and have been.
On iOS there is no problem at all.
Is there anything you might suspect?

**Comment by spydon** [comment]
Is the app done writing to the file and has closed the socket and flushed etc before you try to play from it?

**Comment by RishiKar** [comment]
Hi @spydon the app is done writing to the file. Is there a way for me to check the closure and flushing methods?
Also, on iOS, the exact same code is run. Would there be any platform specific behaviour that would create this?

**Comment by RishiKar** [comment]
@spydon @Gustl22 You were correct. Thank you! It seemed to be a problem of another recording package that was not releasing resources. Hence the error message of prepare failed. I forced disposed and released all resources and then it started working. Crazy that it worked on iOS and not on Android. 
I will close this now

**Comment by spydon** [comment]
Glad you managed to sort it out, and thanks for telling us!

**Comment by YassineChe** [comment]
@RishiKar ,

Can you be more specific ? for me i use source as URL,
Some mp3 file work fine, but some are not.

Can you please explain more?

**Comment by RishiKar** [comment]
@YassineChe I was working with local files. Based on the feedback from the audio players team, I checked if all async functions have finished execution and more importantly audio resources used by other plugins have been released to be consumed by audio players plugin
