### ISSUE TITLE
【1.1.1】audioplayers setSourceUrl() based on flutter-elinux not found on ARM linux devices and weston

### ISSUE THREAD

**Issue by liujuan1018** [bluefireteam/audioplayers#1302]
## Checklist
- [ ] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [ ] I made sure that the issue I am raising doesn't already exist

1.I am able to play audio files on linux ubuntu PC.
2.I am able to play audio files on web.
3. I am unable to play audio files on ARM linux development board and weston.

## Current bug behaviour
I add Flutter code with audioplayers plugin code to Sony flutter-elinux(https://github.com/sony/flutter-elinux/),it build success.
There is an error log when running the flutter app,
arm_release_ver of this libmali is 'g2p0-01eac0', rk_so_ver is '7'.
flutter: The Dart VM service is listening on http://127.0.0.1:41859/8my5k4tgU9Q=/
flutter: ---------------------
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method setSourceUrl on channel xyz.luan/audioplayers)
#0 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:294:7)

## Expected behaviour
Play audio file successfully on ARM linux devices and weston.

## Steps to reproduce

There are full steps to reproduce the problem on weston based on linux platform.
1.Prepare a Sony flutter-elinux enviroment at first. (You can see Quick start at https://github.com/sony/flutter-elinux)
2.Prepare a flutter app code with audioplayer code.
3.Run "sudo apt-get install -y unzip curl clang cmake pkg-config weston" on linux platform.
4.# run weston on linux platform.
weston &
5.cd  <your existing flutter project>
6.export PATH="$PATH:~/flutter-elinux/bin"
7.# run flutter app
flutter-elinux run -d elinux-wayland

1. Execute `flutter run` on the code sample 
2. ... 
4. ... 

<details>
<summary>Code sample</summary>

```dart
void main() {
}
```

</details>

## Logs
arm_release_ver of this libmali is 'g2p0-01eac0', rk_so_ver is '7'.
flutter: The Dart VM service is listening on http://127.0.0.1:41859/8my5k4tgU9Q=/
flutter: ---------------------
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method setSourceUrl on channel xyz.luan/audioplayers)
#0 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:294:7)

```
my relevant logs
```

<details>
  <summary>Full Logs</summary>

  

  ```
  my full logs or a link to a gist
  ```

  Flutter doctor:
  ```
  Output of: flutter doctor -v
  ```
</details>

## Audio Files/URLs/Sources

- Sample Url: https://luan.xyz/files/audio/coins.wav
- Sample Stream: https://example.com/my_stream.m3u8

## Environment information

* audioplayers version:1.1.1

Platform 1: 
* OS name and version: 
Chrome is ok;  Linux PC is ok; Weston on flutter-elinux is not ok;
* Device: 

* build mode: `debug`

* error peculiarities (optional): 

Platforms tested without any issue (optional): 
* test peculiarities:

**Comment by Gustl22** [comment]
See #1154 
Seems like flutter thinks that arm is a different platform than linux. Maybe this is a thing of flutter, but haven't done any research yet.

**Comment by liujuan1018** [comment]
I run the app on elinux with Platform.isLinux code, the result is true. I think the platform of elinux  is linux.
