### ISSUE TITLE
Crash app : Audio Players in android version 5.1.1 (Lollipop) using Flutter

### ISSUE THREAD

**Issue by PiyushSorathiya** [bluefireteam/audioplayers#1306]
## Error
Rejecting re-init on previously-failed class java.lang.Class<xyz.luan.audioplayers.ByteDataSource>
E/AndroidRuntime( 4523): FATAL EXCEPTION: main
E/AndroidRuntime( 4523): Process: com.rajkot.gurukul.mantrajapcount, PID: 4523
E/AndroidRuntime( 4523): java.lang.NoClassDefFoundError: xyz.luan.audioplayers.ByteDataSource
E/AndroidRuntime( 4523): 	at xyz.luan.audioplayers.AudioplayersPlugin.handleMethodCall(AudioplayersPlugin.kt:71)
E/AndroidRuntime( 4523): 	at xyz.luan.audioplayers.AudioplayersPlugin.onMethodCall(AudioplayersPlugin.kt:33)
E/AndroidRuntime( 4523): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/AndroidRuntime( 4523): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/AndroidRuntime( 4523): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/AndroidRuntime( 4523): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
E/AndroidRuntime( 4523): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime( 4523): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 4523): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 4523): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime( 4523): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4523): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 4523): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime( 4523): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
I/Process ( 4523): Sending signal. PID: 4523 SIG: 9

This issue is only on the android lollipop version.

In other devices is working. Please help for getting solution.

I have using audioplayers: ^0.20.1 

## Platforms

Affected Platforms: Android 5.1.1 

## More information (optional)

String audioAsset = "assets/audio/jay_swaminarayan.mp3";
 ByteData bytes = await rootBundle.load(audioAsset); //load audio from assets
 audioBytes = bytes.buffer.asUint8List(bytes.offsetInBytes, bytes.lengthInBytes);
 await _audioPlayer.playBytes(audioBytes);
 
 This is the audio file link:
 https://drive.google.com/file/d/1VF6gqliytFMAoRJONZKRM7Xuiz3ziIKY/view?usp=sharing

**Comment by Gustl22** [comment]
We don't support older versions of audioplayers. Plz update to latest version ^1.x.x

**Comment by interpre** [comment]
I got the same issue on Android Version 12.
version: audioplayers: ^1.1.0

**Comment by bunny-pu** [comment]
same issue and stacktraces in version 0.20.1, app will crash at android api 5.1.1,
 is anyone who use the latest version, and have this issue fixed?
