### ISSUE TITLE
Audio focus request denied due to IllegalArgumentException: Invalid duration hint

### ISSUE THREAD

**Issue by DamonChen117** [bluefireteam/audioplayers#1321]
audioplayers: ^1.1.1

The code works fine in iOS. When running in Android, it reported:

```
E/AudioManager(13140): Audio focus request denied due to 
E/AudioManager(13140): java.lang.IllegalArgumentException: Invalid duration hint
E/AudioManager(13140): 	at android.media.AudioManager.requestAudioFocus(AudioManager.java:2447)
E/AudioManager(13140): 	at android.media.AudioManager.requestAudioFocus(AudioManager.java:2406)
E/AudioManager(13140): 	at android.media.AudioManager.requestAudioFocus(AudioManager.java:2315)
E/AudioManager(13140): 	at xyz.luan.audioplayers.player.FocusManager.oldRequestAudioFocus(FocusManager.kt:62)
E/AudioManager(13140): 	at xyz.luan.audioplayers.player.FocusManager.maybeRequestAudioFocus(FocusManager.kt:28)
E/AudioManager(13140): 	at xyz.luan.audioplayers.player.WrappedPlayer.play(WrappedPlayer.kt:158)
E/AudioManager(13140): 	at xyz.luan.audioplayers.AudioplayersPlugin.handler(AudioplayersPlugin.kt:100)
E/AudioManager(13140): 	at xyz.luan.audioplayers.AudioplayersPlugin.access$handler(AudioplayersPlugin.kt:25)
E/AudioManager(13140): 	at xyz.luan.audioplayers.AudioplayersPlugin$onAttachedToEngine$1$1.invoke(AudioplayersPlugin.kt:41)
E/AudioManager(13140): 	at xyz.luan.audioplayers.AudioplayersPlugin$onAttachedToEngine$1$1.invoke(AudioplayersPlugin.kt:41)
E/AudioManager(13140): 	at xyz.luan.audioplayers.AudioplayersPlugin$safeCall$1.invokeSuspend(AudioplayersPlugin.kt:62)
E/AudioManager(13140): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/AudioManager(13140): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
E/AudioManager(13140): 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
E/AudioManager(13140): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
E/AudioManager(13140): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
E/AudioManager(13140): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
E/AudioManager(13140): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
E/AudioManager(13140): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by clockwork189** [comment]
I also experienced this issue with AndroidAudioFocus.none. Setting the value to anything else, even null, fixed the issue for me. I did get a different stack trace which I am adding below so that it may help with debugging this issue:
```
D/AudioPlayers( 6130): java.lang.IllegalArgumentException: Illegal audio focus gain type 0
D/AudioPlayers( 6130): 	at android.media.AudioFocusRequest$Builder.setFocusGain(AudioFocusRequest.java:405)
D/AudioPlayers( 6130): 	at android.media.AudioFocusRequest$Builder.<init>(AudioFocusRequest.java:373)
D/AudioPlayers( 6130): 	at xyz.luan.audioplayers.player.FocusManager.newRequestAudioFocus(FocusManager.kt:47)
D/AudioPlayers( 6130): 	at xyz.luan.audioplayers.player.FocusManager.maybeRequestAudioFocus(FocusManager.kt:25)
D/AudioPlayers( 6130): 	at xyz.luan.audioplayers.player.WrappedPlayer.play(WrappedPlayer.kt:158)
D/AudioPlayers( 6130): 	at xyz.luan.audioplayers.AudioplayersPlugin.handler(AudioplayersPlugin.kt:100)
D/AudioPlayers( 6130): 	at xyz.luan.audioplayers.AudioplayersPlugin.access$handler(AudioplayersPlugin.kt:25)
D/AudioPlayers( 6130): 	at xyz.luan.audioplayers.AudioplayersPlugin$onAttachedToEngine$1$1.invoke(AudioplayersPlugin.kt:41)
D/AudioPlayers( 6130): 	at xyz.luan.audioplayers.AudioplayersPlugin$onAttachedToEngine$1$1.invoke(AudioplayersPlugin.kt:41)
D/AudioPlayers( 6130): 	at xyz.luan.audioplayers.AudioplayersPlugin$safeCall$1.invokeSuspend(AudioplayersPlugin.kt:62)
D/AudioPlayers( 6130): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
D/AudioPlayers( 6130): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
D/AudioPlayers( 6130): 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
D/AudioPlayers( 6130): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
D/AudioPlayers( 6130): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
D/AudioPlayers( 6130): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
D/AudioPlayers( 6130): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
D/AudioPlayers( 6130): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by thelastknightahk** [comment]
@clockwork189 I also had issues like that. Now, I fixed by deleting build folder

**Comment by rsyd29** [comment]
> Illegal audio focus gain type 0

any update for this. I got same error. If i put this code `audioFocus: AndroidAudioFocus.none`.

**Comment by rsyd29** [comment]
> > Illegal audio focus gain type 0
> 
> any update for this. I got same error. If i put this code
> 
> `android: AudioContextAndroid( isSpeakerphoneOn: true, stayAwake: true, contentType: AndroidContentType.sonification, usageType: AndroidUsageType.assistanceSonification, audioFocus: AndroidAudioFocus.none, ),`

solved with this [link](https://github.com/bluefireteam/audioplayers/issues/1194#issuecomment-1272208575)
