### ISSUE TITLE
[Android] Fatal Exception: java.lang.IllegalStateException

### ISSUE THREAD

**Issue by chenenyu** [bluefireteam/audioplayers#1375]
Crash log:
```
Fatal Exception: java.lang.IllegalStateException:
       at android.media.MediaPlayer.getDuration(MediaPlayer.java)
       at xyz.luan.audioplayers.player.MediaPlayerPlayer.getDuration(MediaPlayerPlayer.kt:26)
       at xyz.luan.audioplayers.player.WrappedPlayer.getDuration(WrappedPlayer.kt:134)
       at xyz.luan.audioplayers.AudioplayersPlugin.handleDuration(AudioplayersPlugin.kt:166)
       at xyz.luan.audioplayers.player.WrappedPlayer.onPrepared(WrappedPlayer.kt:236)
       at xyz.luan.audioplayers.player.MediaPlayerPlayer.createMediaPlayer$lambda$5$lambda$0(MediaPlayerPlayer.kt:16)
       at xyz.luan.audioplayers.player.MediaPlayerPlayer.$r8$lambda$OOBz89UmukEQhjFRdQ_BJ4ztFD4(MediaPlayerPlayer.kt)
       at xyz.luan.audioplayers.player.MediaPlayerPlayer$$InternalSyntheticLambda$1$296514634a2b58642f47b4fbcf9ba89cf596f2246040028ce119ddff1b7069d4$0.onPrepared(MediaPlayerPlayer.java:2)
       at android.media.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:3486)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:264)
       at android.app.ActivityThread.main(ActivityThread.java:8315)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
```

`audioplayers: ^1.1.3`

**Comment by Gustl22** [comment]
This is too less information, please fill the issue template and search for existing issues.
