### ISSUE TITLE
AndroidAudioError java.lang.IllegalStateException during setSourceUrl

### ISSUE THREAD

**Issue by fullflash** [bluefireteam/audioplayers#1611]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

Hi.
sometimes we are getting this exception on setSourceUrl
the audio url is a correct audio file no corrupted source.

### Expected behaviour

correctly play audio file without exception.

### Steps to reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

### Code sample

<details>
<summary>Code sample</summary>

```dart
void main() {
}
```

</details>

### Affected platforms

Android

### AudioPlayers Version

 ^4.1.0

### Logs

```
red>16.08.2023 16:33:20=> PlatformException(AndroidAudioError, null, java.lang.IllegalStateException
at android.media.MediaPlayer.getPlaybackParams(Native Method)
```

<details>
  <summary>Full Logs</summary>

  ```
`red>16.08.2023 16:33:20=> PlatformException(AndroidAudioError, null, java.lang.IllegalStateException
at android.media.MediaPlayer.getPlaybackParams(Native Method)
at zb.i.k(Unknown Source:2)
at zb.o.c(Unknown Source:2)
at zb.o.L(Unknown Source:20)
at yb.m.J(Unknown Source:546)
at yb.m.n(Unknown Source:0)
at yb.m$b.b(Unknown Source:14)
at yb.m$b.invoke(Unknown Source:4)
at yb.m$d.invokeSuspend(Unknown Source:16)
at kotlin.coroutines.jvm.internal.a.resumeWith(Unknown Source:11)
at ab.q0.run(Unknown Source:88)
at kotlinx.coroutines.internal.k.run(Unknown Source:12)
at kotlinx.coroutines.scheduling.k.run(Unknown Source:2)
at kotlinx.coroutines.scheduling.a.D(Unknown Source:0)
at kotlinx.coroutines.scheduling.a$c.d(Unknown Source:14)
at kotlinx.coroutines.scheduling.a$c.n(Unknown Source:28)
at kotlinx.coroutines.scheduling.a$c.run(Unknown Source:0)
, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310)
<asynchronous suspension>
#2      AudioPlayer._completePrepared (package:audioplayers/src/audioplayer.dart:301)
<asynchronous suspension>
#3      AudioPlayer.setSourceUrl (package:audioplayers/src/audioplayer.dart:313)
<asynchronous suspension>
#4      AudioPlayer.setSource (package:audioplayers/src/audioplayer.dart:284)
<asynchronous suspension>`
  ```

  Flutter doctor:
  ```
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.5 22G74 darwin-arm64, locale
    en-AZ)
    • Flutter version 3.10.6 on channel stable at

    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (5 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/****android
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/****l/android
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.5 22G74 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 115.0.5790.170

[✓] Network resources
    • All expected network resources are available.

• No issues found!
  ```
</details>

### Working on PR

no way

**Comment by Gustl22** [comment]
In order to rerpoduce we need the audio file :)

**Comment by fullflash** [comment]
@Gustl22 thanks for reply unfortunately audio is recorded voice that's why has no permission to share.
but i have download and the audio file is playable also it is playable with this plugin.
i have checked all illegalstateexception issues but the stack is different

**Comment by Gustl22** [comment]
Not every source is playable on every device or operatiing system. Did you read the troubleshooting guide? Especially the part with the supported file encodings?
https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md#supported-formats--encodings

If you can play it with the native android player, you should also be able to play it with `audioplayers`.

**Comment by fullflash** [comment]
the remote audio url that was subject of this exception is playable correctly with audioplayers library.
this exception happens sometimes but later it play with no issue.
so this is not about codec or platform depended issue.

**Comment by fullflash** [comment]
according this comment maybe resetting mediaplayer can prevent this exception to be happened.
(https://github.com/react-native-video/react-native-video/issues/1061#issuecomment-399566392)

**Comment by Gustl22** [comment]
I see, I agrree with [cobarx](https://github.com/cobarx) that this is probably not sth we should deal with, especially if it only occurs on certain devices. And more focus on implementing ExoPlayer, see #1526

**Comment by giantss** [comment]
I have also found a lot of such problems in the error information collected through `Firebase Crashlytics`.

<img width="1243" alt="image" src="https://github.com/user-attachments/assets/fb9d6527-6c80-4d0b-a806-f973e8478089">
