### ISSUE TITLE
No signature of method:

### ISSUE THREAD

**Issue by wrjcs** [bluefireteam/audioplayers#1657]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

FAILURE: Build completed with 2 failures.
[   +4 ms] 1: Task failed with an exception.
[   +2 ms] -----------
[   +1 ms] * Where:
[   +1 ms] Build file 'C:\Users\weshop\AppData\Local\Pub\Cache\hosted\pub.dev\audioplayers_android-4.0.1\android\build.gradle' line: 31
[   +1 ms] * What went wrong:
[   +2 ms] A problem occurred evaluating project ':audioplayers_android'.
[   +1 ms] > No signature of method: build_92a1c8vpxl9kjj6trvf67xwqu.android() is applicable for argument types: (build_92a1c8vpxl9kjj6trvf67xwqu$_run_closure2) values:
[build_92a1c8vpxl9kjj6trvf67xwqu$_run_closure2@73eec00e]
[   +3 ms] * Try:
[   +1 ms] Run with --debug option to get more log output. Run with --scan to get full insights.
[   +1 ms] * Exception is:
[   +1 ms] org.gradle.api.GradleScriptException: A problem occurred evaluating project ':audioplayers_android'.
[   +1 ms]      at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:93)
[   +1 ms]      at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.lambda$apply$0(DefaultScriptPluginFactory.java:133)

### Expected behaviour

Hello,
I update my flutter from 3.10.* to 3.13.*
When I compile my code, I got this error.

### Steps to reproduce

1.upgrade flutter to 3.13.6
2.compile code : flutter build apk --split-per-abi -v 

### Code sample

<details>
<summary>Code sample</summary>

```dart
void main() {
}
```

</details>

### Affected platforms

Android

### AudioPlayers Version

5.1.0

### Build mode

release

### Logs

```
my relevant logs
```

<details>
  <summary>Full Logs</summary>

  

  ```
  my full logs or a link to a gist
  ```

  Flutter doctor:
  ```
  Output of: flutter doctor -v
  ```
</details>

### Working on PR

no way

**Comment by Gustl22** [comment]
Did you try a `flutter clean` beforehand? What happens on just `flutter build apk -v`? How does your build.gradle file look like? Did you compare it to the one in [example](https://github.com/bluefireteam/audioplayers/blob/main/packages/audioplayers/example/android/build.gradle)?

**Comment by vbuberen** [comment]
This error appears when the project uses Android Gradle Plugin older than `4.2.0`.

Find `build.gradle` file in `android` folder of your project, find `classpath 'com.android.tools.build:gradle` line and update its version to some fresh versions like 7.x.x or 8.x.x.

Considering that you already have old version of Android Gradle Plugin after updating it you might also need to update Gradle wrapper version. To do so find `gradle-wrapper.properties`, find `distributionUrl` line and replace it something like this to update to Gradle 8.3:
```distributionUrl=https\://services.gradle.org/distributions/gradle-8.3-bin.zip```
