### ISSUE TITLE
Shipping broken, doesn't work 

### ISSUE THREAD

**Issue by s1nistr4** [bluefireteam/audioplayers#1699]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

I follow the exact instructions and just get this 

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown while applying parent data.:
Incorrect use of ParentDataWidget.
The ParentDataWidget Flexible(flex: 1) wants to apply ParentData of type FlexParentData to a
RenderObject, which has been set up to accept ParentData of incompatible type ParentData.
Usually, this means that the Flexible widget has the wrong ancestor RenderObjectWidget. Typically,
Flexible widgets are placed directly inside Flex widgets.
The offending Flexible is currently placed inside a SizedBox widget.
The ownership chain for the RenderObject that received the incompatible parent data was:
  RichText ← Text ← Flexible ← StartText ← SizedBox ← Column ← Row ← Center ← Column ← Padding ← ⋯

When the exception was thrown, this was the stack:
#0      RenderObjectElement._updateParentData.<anonymous closure> (package:flutter/src/widgets/framework.dart:6230:11)
#1      RenderObjectElement._updateParentData (package:flutter/src/widgets/framework.dart:6247:6)
#2      RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:6270:7)
#3      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6154:5)
#4      MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6576:11)
...     Normal element mounting (22 frames)
#26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4182:16)
#27     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6569:36)
#28     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6581:32)
#29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4182:16)
#30     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6569:36)
#31     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6581:32)
...     Normal element mounting (4 frames)
#35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4182:16)
#36     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6569:36)
#37     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6581:32)
...     Normal element mounting (37 frames)
#74     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4182:16)
#75     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6569:36)
#76     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6581:32)
...     Normal element mounting (330 frames)
#406    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4182:16)
#407    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6569:36)
#408    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6581:32)
...     Normal element mounting (452 frames)
#860    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4182:16)
#861    Element.updateChild (package:flutter/src/widgets/framework.dart:3707:18)
#862    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1253:16)
#863    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1222:5)
#864    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1169:18)
#865    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2719:19)
#866    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1168:13)
#867    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:1001:7)
#868    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:981:7)
#872    _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
(elided 3 frames from class _Timer and dart:async-patch)
```

### Expected behaviour

For it to play audio

### Steps to reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

### Code sample

<details>
<summary>Code sample</summary>

```dart
void main() {
}
```

</details>

### Affected platforms

Windows

### Platform details

Windows 11

### AudioPlayers Version

.

### Logs

```
my relevant logs
```

<details>
  <summary>Full Logs</summary>

  

  ```
  my full logs or a link to a gist
  ```

  Flutter doctor:
  ```
  Output of: flutter doctor -v
  ```
</details>

### Working on PR

no way

**Comment by Gustl22** [comment]
Hey there. I don't see anything related to AudioPlayers. Which instructions did you use? What is the code base?
