### ISSUE TITLE
example build failure [3.13.9]

### ISSUE THREAD

**Issue by jwinarske** [bluefireteam/audioplayers#1707]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

```
lib/tabs/audio_context.dart:214:65: Error: The argument type
'Set<AVAudioSessionOptions>' can't be assigned to the parameter type
'List<AVAudioSessionOptions>?'.
 - 'Set' is from 'dart:core'.
 - 'AVAudioSessionOptions' is from
 'package:audioplayers_platform_interface/src/api/audio_context.dart'
 ('../../../../../.config/flutter_workspace/pub_cache/hosted/pub.dev/audiopl
 ayers_platform_interface-6.1.0/lib/src/api/audio_context.dart').
 - 'List' is from 'dart:core'.
              final iosContext = audioContext.iOS.copy(options: options);
                                                                ^
Target kernel_snapshot failed: Exception
#0      KernelSnapshot.build (package:flutter_tools/src/build_system/targets/common.dart:256:7)
<asynchronous suspension>
#1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:853:9)
<asynchronous suspension>
#2      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
<asynchronous suspension>
#3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:791:32)
<asynchronous suspension>
#4      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:620:16)
<asynchronous suspension>
#5      BundleBuilder.build (package:flutter_tools/src/bundle_builder.dart:75:32)
<asynchronous suspension>
#6      BuildBundleCommand.runCommand (package:flutter_tools/src/commands/build_bundle.dart:129:5)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
<asynchronous suspension>
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>

Failed to build bundle.
```

### Expected behaviour

`flutter build bundle` should succeed.

### Steps to reproduce

1. flutter build bundle

### Code sample

<details>
<summary>Code sample</summary>

```dart
void main() {
}
```

</details>

### Affected platforms

Linux

### Platform details

* Fedora 38

### AudioPlayers Version

main, 5.2.1

### Build mode

debug

### Logs

```
my relevant logs
```

<details>
  <summary>Full Logs</summary>

  

  ```
  my full logs or a link to a gist
  ```

  Flutter doctor:
  ```
  Output of: flutter doctor -v
  ```
</details>

### Working on PR

no way

**Comment by Gustl22** [comment]
See https://github.com/bluefireteam/audioplayers/blob/main/contributing.md#environment-setup

**Comment by jwinarske** [comment]
that did it!  thanks :)
