### ISSUE TITLE
Constant crash on android 6.0.1

### ISSUE THREAD

**Issue by ehtiqamar** [bluefireteam/audioplayers#1727]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

After the update to audioplayers 5.2.1, there is constant crash of IlllegalStateException on Android 6.0.1 devices. 

### Expected behaviour

The player should play the audio from assets.

### Steps to reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

### Code sample

  Future<void> play(String fileName, {bool loop = false}) async {
    if (_audioPlayer.state == PlayerState.disposed) {
      _audioPlayer = AudioPlayer();
    }
    await _audioPlayer.release();
    _audioPlayer.play(AssetSource('sounds/$fileName'), volume: _volume);
    if (loop) {
      _audioPlayer.setReleaseMode(ReleaseMode.loop);
    }
  }

### Affected platforms

Android

### Platform details

Platform: Android 6.0.1

### AudioPlayers Version

5.2.1

### Build mode

release

### Logs

Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: PlatformException(AndroidAudioError, null, java.lang.IllegalStateException
	at android.media.MediaPlayer.prepareAsync(Native Method)
	at n9.i.d()
	at n9.o.N()
	at m9.m.J()
	at m9.m.n()
	at m9.m$b.b()
	at m9.m$b.invoke()
	at m9.m$d.invokeSuspend()
	at kotlin.coroutines.jvm.internal.a.resumeWith()
	at d9.d1.run()
	at kotlinx.coroutines.internal.n.run()
	at kotlinx.coroutines.scheduling.k.run()
	at kotlinx.coroutines.scheduling.a.M()
	at kotlinx.coroutines.scheduling.a$c.d()
	at kotlinx.coroutines.scheduling.a$c.n()
	at kotlinx.coroutines.scheduling.a$c.run()
, null)
       at StandardMethodCodec.decodeEnvelope(message_codecs.dart:652)
       at MethodChannel._invokeMethod(platform_channel.dart:310)
       at AudioPlayer.stop(audioplayer.dart:226)
       at AudioPlayer.release(audioplayer.dart:242)
       at AudioPlayer.dispose(audioplayer.dart:405)
       at AudioManager._disposeMusic(audio_manager.dart:112)
       at AudioManager.dispose(audio_manager.dart:99)

### Working on PR

no way

**Comment by Gustl22** [comment]
Try to set the release mode before playing.
Also use `await` before `setReleaseMode` and `play`.

See also #1526

**Comment by ehtiqamar** [comment]
> Try to set the release mode before playing. Also use `await` before `setReleaseMode` and `play`.
> 
> See also #1526

Ok, I'll try with await, but I don't think that would be cause since this only happens on Android 6.0.1

**Comment by tkortekaas** [comment]
@ehtiqamar did you find a solution? I am also struggling with this for Android 6 devices in specific

**Comment by ehtiqamar** [comment]
> @ehtiqamar did you find a solution? I am also struggling with this for Android 6 devices in specific

nope, I tried the above solution but it is still crashing

**Comment by echogit** [comment]
Same here, and the worst is that I don't know which of is the exactly place it is crashing:
```
PlatformException(AndroidAudioError, null, java.lang.IllegalStateException
	at android.media.MediaPlayer.prepareAsync(Native Method)
	at q2.i.prepare(MediaPlayerWrapper.kt:3)
	at q2.r.J(WrappedPlayer.kt:50)
	at p2.d.d(AudioplayersPlugin.kt:426)
	at p2.c.invoke(AudioplayersPlugin.kt:48)
	at p2.d.a(AudioplayersPlugin.kt:20)
	at p2.b.onMethodCall(R8$$SyntheticClass:14)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:18)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:12)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0(DartMessenger.java:35)
	at io.flutter.embedding.engine.dart.DartMessenger.a(DartMessenger.java:1)
	at io.flutter.embedding.engine.dart.a.run(R8$$SyntheticClass:13)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:7325)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
, null)
       at StandardMethodCodec.decodeEnvelope(message_codecs.dart:652)
       at MethodChannel._invokeMethod(platform_channel.dart:370)
       at AudioPlayer.stop(audioplayer.dart:256)
```
