### ISSUE TITLE
PlatformException(DarwinAudioError, Error configuring audio session: Error Domain=NSOSStatusErrorDomain Code=-50 "(null)", null, null)

### ISSUE THREAD

**Issue by nagringapp** [bluefireteam/audioplayers#1740]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

I often get the following error on my console.

lutter: \^[[38;5;196m┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<…>
flutter: \^[[38;5;196m│ PlatformException(DarwinAudioError, Error configuring audio session: Error Domain=NSOSStatusErrorDomain Code=-50 "(null)", null, null)<…>
flutter: \^[[38;5;196m├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄<…>
flutter: \^[[38;5;196m│ #0   StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)<…>
flutter: \^[[38;5;196m│ #1   MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)<…>
flutter: \^[[38;5;196m│ #2   <asynchronous suspension><…>
flutter: \^[[38;5;196m├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄<…>
flutter: \^[[38;5;196m│ ⛔ Global Error<…>
flutter: \^[[38;5;196m└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<…>
flutter: ----------------FIREBASE CRASHLYTICS----------------
flutter: PlatformException(DarwinAudioError, Error configuring audio session: Error Domain=NSOSStatusErrorDomain Code=-50 "(null)", null, null)
flutter: 
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
<asynchronous suspension>
flutter: ----------------------------------------------------
[Global Error] Global Error
[Global Error] PlatformException (PlatformException(DarwinAudioError, Error configuring audio session: Error Domain=NSOSStatusErrorDomain Code=-50 "(null)", null, null))
[Global Error] #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
               #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
               <asynchronous suspension>

### Expected behaviour

Playe without errors

### Steps to reproduce

Just play the music - see code below

### Code sample

<details>
<summary>Code sample</summary>

```dart
oid _initAudioPlayer(String url) async {
    
    try {
      
      _audioPlayer = AudioPlayer(playerId: _musicId);
      _audioPlayer.setAudioContext(const AudioContext(
        android: AudioContextAndroid(
          contentType: AndroidContentType.music,
          isSpeakerphoneOn: true,
          stayAwake: true,
          usageType: AndroidUsageType.media,
          audioFocus: AndroidAudioFocus.gainTransientExclusive
        ),
        iOS: AudioContextIOS(
          category: AVAudioSessionCategory.multiRoute,
          options: [
            AVAudioSessionOptions.allowAirPlay, 
            AVAudioSessionOptions.allowBluetooth,
            AVAudioSessionOptions.allowBluetoothA2DP,
            AVAudioSessionOptions.defaultToSpeaker,
            AVAudioSessionOptions.interruptSpokenAudioAndMixWithOthers
          ],
        )
      ));

      await _audioPlayer.play(UrlSource(url));
      
      
    } catch (e, s) {
      Log.error('EsquentaPlayer._init', e, s);

    }
  }
```

</details>

### Affected platforms

Android, iOS

### AudioPlayers Version

5.2.1

### Build mode

debug

### Logs

```
my relevant logs
```

<details>
  <summary>Full Logs</summary>

  

  ```
  my full logs or a link to a gist
  ```

  Flutter doctor:
  ```
  Output of: flutter doctor -v
  ```
</details>

### Working on PR

no way

**Comment by cgfischer** [comment]
I am experiencing the same problem.  Any update or work-around?

**Comment by nagringapp** [comment]
I noticed in dev mode the app has been crashing a lot, but i couldt map the
bug in production yet. (So im concerned if it will crash the user at some
point).

No work around - kill the app and run it again that my workaround.

Kind Regards,

*Thiago Bernardes*
Founder
0448 087 563
www.nagringa.app
<https://www.hungy.app/?utm_source=signature&utm_medium=email&utm_campaign=contact-tb>

**Comment by jozes** [comment]
Any progress on this matter? Or workaround?

Interestingly I get the same error only when running on IOS in release mode (on physical device). However, I get no error when running in simulator in debug mode. So this is really annoying. 
While digging deeper I found that the error is reported from SwiftAudioPlayersDarwinPlugin.swift when the method is "setAudioContext". In my code I had the following line:  

AudioPlayer.global.setAudioContext(audioContext)

which was causing the error and I could not get rid of it although I put in try/catch block. As I am using package Catcher to catch and report errors I found that the app is playing audio when I just continued after getting this error. 
So my solution was just to comment this line and everything works as supposed.

**Comment by nagringapp** [comment]
By the way, I was checking my logs in production and I can see those events
coming through. However, I don’t know if the app is crashing with the user.

Kind Regards,

*Thiago Bernardes*
Founder
0448 087 563
www.nagringa.app
<https://www.hungy.app/?utm_source=signature&utm_medium=email&utm_campaign=contact-tb>

**Comment by jozes** [comment]
@nagringapp 
In my app I am using Catcher to catch all uncaught exceptions and this one was always triggering Catcher to display the error to the app user. So in my case the app was crashing in a "controllable" way reporting an exception via Catcher screen.  Interesting, no such exception is occurring in debug mode.

**Comment by Gustl22** [comment]
Thank you for the detailed report. I currently have no OSX machine. But I try to solve this at some point. Don't hesitate trying to fix it and post a Merge Request. Thank you!
