### ISSUE TITLE
Sound not found inside cache folder - app crash

### ISSUE THREAD

**Issue by prok155** [bluefireteam/audioplayers#1778]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

I published my app to google play store, I use crashlytics and I see following stacktraces:

`PlatformException(AndroidAudioError, Failed to set source. For troubleshooting, see: https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md, java.io.FileNotFoundException: /data/user/0/com.companyname.myPackageName/cache/audio/AnswerCorrect.mp3: open failed: ENOENT (No such file or directory) at libcore.io.IoBridge.open(IoBridge.java:574) at java.io.FileInputStream.<init>(FileInputStream.java:160) at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1272) at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1243) at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1208) at ra.d.a(Unknown Source:7) at qa.m.h(Unknown Source:10) at qa.s.K(Unknown Source:15) at pa.m.L(Unknown Source:552) at pa.m.o(Unknown Source:0) at pa.m$b.b(Unknown Source:14) at pa.m$b.invoke(Unknown Source:4) at pa.m$d.invokeSuspend(Unknown Source:16) at kotlin.coroutines.jvm.internal.a.resumeWith(Unknown Source:11) at ba.y0.run(Unknown Source:93) at ga.o$a.run(Unknown Source:3) at ia.k.run(Unknown Source:2) at ia.a.R(Unknown Source:0) at ia.a$c.d(Unknown Source:14) at ia.a$c.p(Unknown Source:28) at ia.a$c.run(Unknown Source:0) Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory) at libcore.io.Linux.open(Native Method) at libcore.io.ForwardingOs.open(ForwardingOs.java:563) at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274) at libcore.io.ForwardingOs.open(ForwardingOs.java:563) at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8641) at libcore.io.IoBridge.open(IoBridge.java:560) ... 20 more , null)`

I have my sound files in my 'assets', but it seems that your package creates sounds files inside temp `cache` directory, look : `java.io.FileNotFoundException: /data/user/0/com.companyname.myPackageName/cache/audio/AnswerCorrect.mp3`.

Android sometimes deletes `cache` directory, for example when there is not enough space on the disk, you should keep those temp files inside app data directory instead of temp folder.

### Expected behaviour

You should not keep temp files inside `cache` folder, it will fix this issue.

### Steps to reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

### Code sample

<details>
<summary>Code sample</summary>

```dart
void main() {
}
```

</details>

### Affected platforms

Android

### AudioPlayers Version

6.0.0

### Build mode

debug, profile, release

### Logs

```
my relevant logs
```

<details>
  <summary>Full Logs</summary>

  

  ```
  my full logs or a link to a gist
  ```

  Flutter doctor:
  ```
  Output of: flutter doctor -v
  ```
</details>

### Working on PR

no way

**Comment by prok155** [comment]
If I do somthing wrong, please explain me how can I fix this issue.

**Comment by IRiS-Sk13** [comment]
+1 I'm facing this a lot too

**Comment by hanshanfeihe** [comment]
+1

**Comment by N3PH1L4X** [comment]
+1

**Comment by martinpelli** [comment]
Same here 
```
 Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: PlatformException(AndroidAudioError, Failed to set source. For troubleshooting, see: https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md, java.io.FileNotFoundException: /data/user/0/myproject/sounds/fail.mp3: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:574)
	at java.io.FileInputStream.<init>(FileInputStream.java:160)
	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1278)
	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1245)
	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1210)
	at b7.d.a(SourceFile:8)
	at a7.g.k(SourceFile:13)
	at a7.o.i(SourceFile:41)
	at G6.f.h(SourceFile:845)
	at Z6.b.onMethodCall(SourceFile:74)
	at y5.n.a(SourceFile:26)
	at A.B.run(SourceFile:143)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8782)
	at libcore.io.IoBridge.open(IoBridge.java:560)
	... 19 more
, null)
       at StandardMethodCodec.decodeEnvelope(message_codecs.dart:653)
       at MethodChannel._invokeMethod(platform_channel.dart:367)
       at Future.wait.<fn>(dart:async)
       at AudioPlayer._completePrepared(audioplayer.dart:369)
       at AudioPlayer.setSourceAsset(audioplayer.dart:426)
       at AudioPlayer.setSource(audioplayer.dart:352)
       at AudioPlayer.play(audioplayer.dart:218)
```
