### ISSUE TITLE
PlatformException(DarwinAudioError, setSourceBytes is not currently implemented on iOS,

### ISSUE THREAD

**Issue by sufiyanas** [bluefireteam/audioplayers#1782]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

<asynchronous suspension>
#3      AudioPlayer.setSourceBytes (package:audioplayers/src/audioplayer.dart:370:5)
<asynchronous suspension>
#4      AudioPlayer.setSource (package:audioplayers/src/audioplayer.dart:300:5)
<asynchronous suspension>
#5      AudioPlayer.play (package:audioplayers/src/audioplayer.dart:195:5)
<asynchronous suspension>
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(DarwinAudioError, setSourceBytes is not currently implemented on iOS, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:322:18)
<asynchronous suspension>
#2      AudioPlayer._completePrepared (package:audioplayers/src/audioplayer.dart:320:5)
<asynchronous suspension>

### Expected behaviour

i am trying to create a voice chat application , When i run the application in ios i am facing this issue.

### Steps to reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

### Code sample

<details>
<summary>Code sample</summary>

```dart
void main() {
}
```

</details>

### Affected platforms

iOS

### AudioPlayers Version

  audioplayers: ^5.2.1

### Screenshots

<img width="1083" alt="image" src="https://github.com/bluefireteam/audioplayers/assets/76591972/db306836-c0a9-4499-81a9-3ad709afab19">

### Logs

```
my relevant logs
```

<details>
  <summary>Full Logs</summary>

  

  ```
  my full logs or a link to a gist
  ```

  Flutter doctor:
  ```
  Output of: flutter doctor -v
  ```
</details>

### Working on PR

no way

**Comment by Gustl22** [comment]
Hi there, plz upgrade to v6.0.0. Also make sure to run it with XCode 15.

**Comment by sufiyanas** [comment]
Hi, thank you for your response. 
I have updated both , My current Xcode version is 15.3 and audio player V6.0.0 Still i am facing same issue

**Comment by Gustl22** [comment]
That's weird. Did you try a `flutter clean` and a `flutter pub upgrade`? Make sure the version also changes im the `pubspec.lock`.
