### ISSUE TITLE
Doesn't work on WEB

### ISSUE THREAD

**Issue by SzymonDziak** [bluefireteam/audioplayers#1810]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

doesn't work on web after deployment. works on local.

### Expected behaviour

to work

### Steps to reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

### Code sample

<details>
<summary>Code sample</summary>

```dart
void main() {
}
```

</details>

### Affected platforms

web

### AudioPlayers Version

latest

### Build mode

release

### Logs

```
my relevant logs
```

<details>
  <summary>Full Logs</summary>

  

  ```
  my full logs or a link to a gist
  ```

  Flutter doctor:
  ```
  Output of: flutter doctor -v
  ```
</details>

### Working on PR

no way

**Comment by mussymakda** [comment]
> ### Checklist
> * [x]  I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
> * [x]  I made sure that the issue I am raising doesn't already exist
> 
> ### Current bug behaviour
> doesn't work on web after deployment. works on local.
> 
> ### Expected behaviour
> to work
> 
> ### Steps to reproduce
> 1. Execute `flutter run` on the code sample
> 2. ...
> 3. ...
> 
> ### Code sample
> Code sample
> ### Affected platforms
> web
> 
> ### Platform details
> _No response_
> 
> ### AudioPlayers Version
> latest
> 
> ### Build mode
> release
> 
> ### Audio Files/URLs/Sources
> _No response_
> 
> ### Screenshots
> _No response_
> 
> ### Logs
> ```
> my relevant logs
> ```
> 
> Full Logs
> ### Related issues / more information
> _No response_
> 
> ### Working on PR
> no way

facing the same issue please help

**Comment by dvmatyun** [comment]
This one helped me: (building with no-optimization flag). But you may try other flags as well
flutter build web --web-renderer canvaskit --profile --dart-define=Dart2jsOptimization=O0

**Comment by mussymakda** [comment]
> This one helped me: (building with no-optimization flag). But you may try other flags as well flutter build web --web-renderer canvaskit --profile --dart-define=Dart2jsOptimization=O0

not working even in debug web.. worked once but cannot reproduce the issue.

also works fine on android builds.

**Comment by dvmatyun** [comment]
> > This one helped me: (building with no-optimization flag). But you may try other flags as well flutter build web --web-renderer canvaskit --profile --dart-define=Dart2jsOptimization=O0
> 
> not working even in debug web.. worked once but cannot reproduce the issue.
> 
> also works fine on android builds.

hmmm, for me this code works:
`final bytes = await rootBundle.load(audio.path); // 'assets/${audio.path}'
    debugPrint(' > settings audio: ${audio.path} (bytes loaded)');
    final ulist = bytes.buffer.asUint8List();
    debugPrint(' > settings audio: ${audio.path} (ulist loaded)');
    await Future<void>.delayed(Duration.zero);
    final bytesSource = BytesSource(ulist);`
Result is here in my web flutter game after login
https://make-world-strategy.web.app/

**Comment by futurbyte-muhammadhassan** [comment]
Still not working in Release(Build), working only on Debug Mode... Getting error on Release mode...

```
main.dart.js:5660 Uncaught Error: MissingPluginException(No implementation found for method create on channel xyz.luan/audioplayers)
    at Object.c (main.dart.js:5660:19)
    at main.dart.js:146110:15
    at c58.a (main.dart.js:7061:63)
    at c58.$2 (main.dart.js:73709:14)
    at c3m.$1 (main.dart.js:73703:21)
    at aEN.agD (main.dart.js:74872:34)
    at bTI.$0 (main.dart.js:74144:11)
    at Object.SC (main.dart.js:7208:40)
    at aB.zB (main.dart.js:74066:3)
    at bTB.$0 (main.dart.js:74114:13)
```

**Comment by Kurczaak** [comment]
I've encountered the same error on my deployed app. Any suggestions?

**Comment by nietsmmar** [comment]
This is still not working. Is there any idea why this is happening?

**Comment by luanpotter** [comment]
Awesome!
