### ISSUE TITLE
Local file plays when online, but wont play when offline.

### ISSUE THREAD

**Issue by cmcoffeedev** [bluefireteam/audioplayers#516]
I always play the file from a saved path and it works perfectly online. When I try to play it offline I get this stacktrace:

```
E/flutter ( 9516): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Unsupported value: java.lang.IllegalStateException, null)
E/flutter ( 9516): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter ( 9516): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter ( 9516): <asynchronous suspension>
E/flutter ( 9516): #2      AudioPlayer._invokeMethod (package:audioplayers/audioplayers.dart:319:10)
E/flutter ( 9516): #3      AudioPlayer.setUrl (package:audioplayers/audioplayers.dart:518:12)
E/flutter ( 9516): #4      _PlayStoryState._loadFile (package:chris_app_test/PlayMusic.dart:264:19)
E/flutter ( 9516): <asynchronous suspension>
E/flutter ( 9516): #5      _PlayStoryState.initState (package:chris_app_test/PlayMusic.dart:134:5)
E/flutter ( 9516): #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4355:58)
E/flutter ( 9516): #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter ( 9516): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter ( 9516): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter ( 9516): #10     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter ( 9516): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter ( 9516): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter ( 9516): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter ( 9516): #14     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter ( 9516): #15     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter ( 9516): #16     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter ( 9516): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter ( 9516): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter ( 9516): #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter ( 9516): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter ( 9516): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter ( 9516): #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter ( 9516): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter ( 9516): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter ( 9516): #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter ( 9516): #26     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter ( 9516): #27     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter ( 9516): #28     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
E/flutter ( 9516): #29     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter ( 9516): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter ( 9516): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter ( 9516): #32     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter ( 9516): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter ( 9516): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter ( 9516): #35     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter ( 9516): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter ( 9516): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter ( 9516): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter ( 9516): #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter ( 9516): #40     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter ( 9516): #41     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
E/flutter ( 9516): #42     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter ( 9516): #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter ( 9516): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter ( 9516): #45
```

I'm going to fork this and try a fix if it's not able to be duplicated soon.

I'm using version:
 audioplayers: ^0.15.1

Looking at my flutter version, that may be the issue. I'll try that first and update as well. My current version is :
 1.12.13+hotfix.5

FYI, I switched this version before because one of the updates after this one broke my app in the past.

**Comment by luanpotter** [comment]
What is the code you have to actually play the audio (the line in which you can play/setUrl)? Are you really providing a local file with the isLocal flag?

**Comment by cmcoffee91** [comment]
Yes I had that flag set. In the initialize function I had for it, I had the url in case the file didn't download yet. In the play function, I even checked if it was local and called setUrl again with the local file. The fix I ended up doing was just setting an empty string path in setUrl of the initialize function.

**Comment by Gustl22** [comment]
Hi @cmcoffeedev can you check, is this still a thing with 1.x.x? Thx :)
Also it would be good to provide an example, if it still fails.

**Comment by Gustl22** [comment]
Closing as stale.
