### ISSUE TITLE
AudioplayersPlugin.handleDuration() must be executed on the main thread

### ISSUE THREAD

**Issue by mingchaogui** [bluefireteam/audioplayers#702]
**Log Errors**
`2020-12-22 14:55:38.872 31208-31332/com.jt.callmi E/AndroidRuntime: FATAL EXCEPTION: Thread-8
    Process: com.jt.callmi, PID: 31208
    java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-8
        at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:992)
        at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:736)
        at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:72)
        at io.flutter.embedding.engine.dart.DartExecutor$DefaultBinaryMessenger.send(DartExecutor.java:381)
        at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:179)
        at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:97)
        at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:83)
        at xyz.luan.audioplayers.AudioplayersPlugin.handleDuration(AudioplayersPlugin.java:190)
        at xyz.luan.audioplayers.WrappedMediaPlayer.onPrepared(WrappedMediaPlayer.java:348)
        at android.media.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:3420)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at com.superrtc.util.LooperExecutor.run(Unknown Source:36)`

**Screenshots**
![20201222151216](https://user-images.githubusercontent.com/5003855/102860143-3156ed00-4468-11eb-8d43-478a4c6ae685.jpg)

* OS: MIUI 12.0.4.0
* OS version: Android 10
* Device: RedMi Note 8
* flutter version: 1.22.5
* audioplayers version: 0.17.0

**Comment by Gustl22** [comment]
Is this still a thing with `audioplayers: ^1.1.0` ?

**Comment by Gustl22** [comment]
Closing as stale.
