### ISSUE TITLE
[Android 12] IOException when using MediaPlayer.setDataSource

### ISSUE THREAD

**Issue by jja08111** [bluefireteam/audioplayers#978]
### Full Description
I'm testing my app for Android 12. This plugin is working, but the log prints the exception like below when using `play()` not `playBytes()`.

### Code to Reproduce
Change build.gradle targetSdkVersion to 31, insert `android:exported="true"` to AndroidManifest and running example app.

### Log Errors
```console 
D/FileUtils(15391): Failed to convert to modern format file descriptor
D/FileUtils(15391): java.io.IOException: java.lang.IllegalStateException: java.io.IOException: stat failed: ENOENT (No such file or directory)
D/FileUtils(15391): 	at android.provider.MediaStore.getOriginalMediaFormatFileDescriptor(MediaStore.java:939)
D/FileUtils(15391): 	at android.os.FileUtils.convertToModernFd(FileUtils.java:1470)
D/FileUtils(15391): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1274)
D/FileUtils(15391): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1257)
D/FileUtils(15391): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1214)
D/FileUtils(15391): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1191)
D/FileUtils(15391): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1156)
D/FileUtils(15391): 	at xyz.luan.audioplayers.WrappedMediaPlayer.setUrl(WrappedMediaPlayer.kt:37)
D/FileUtils(15391): 	at xyz.luan.audioplayers.AudioplayersPlugin.handleMethodCall(AudioplayersPlugin.kt:59)
D/FileUtils(15391): 	at xyz.luan.audioplayers.AudioplayersPlugin.onMethodCall(AudioplayersPlugin.kt:34)
D/FileUtils(15391): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
D/FileUtils(15391): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
D/FileUtils(15391): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
D/FileUtils(15391): 	at android.os.MessageQueue.nativePollOnce(Native Method)
D/FileUtils(15391): 	at android.os.MessageQueue.next(MessageQueue.java:335)
D/FileUtils(15391): 	at android.os.Looper.loopOnce(Looper.java:161)
D/FileUtils(15391): 	at android.os.Looper.loop(Looper.java:288)
D/FileUtils(15391): 	at android.app.ActivityThread.main(ActivityThread.java:7829)
D/FileUtils(15391): 	at java.lang.reflect.Method.invoke(Native Method)
D/FileUtils(15391): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
D/FileUtils(15391): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:982)
D/FileUtils(15391): Caused by: java.lang.IllegalStateException: java.io.IOException: stat failed: ENOENT (No such file or directory)
D/FileUtils(15391): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2433)
D/FileUtils(15391): 	at android.os.Parcel.createException(Parcel.java:2409)
D/FileUtils(15391): 	at android.os.Parcel.readException(Parcel.java:2392)
D/FileUtils(15391): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
D/FileUtils(15391): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
D/FileUtils(15391): 	at android.content.ContentProviderProxy.call(ContentProviderNative.java:732)
D/FileUtils(15391): 	at android.content.ContentResolver.call(ContentResolver.java:2450)
D/FileUtils(15391): 	at android.provider.MediaStore.getOriginalMediaFormatFileDescriptor(MediaStore.java:935)
D/FileUtils(15391): 	... 20 more
```

### flutter doctor -v
```console
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1110], locale ko-KR)
    • Flutter version 2.2.3 at C:\flutter
    • Framework revision f4abaa0735 (5 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\AndroidSDK
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = C:\AndroidSDK
    • ANDROID_SDK_ROOT = C:\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.58.2)
    • VS Code at C:\Users\민성\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[√] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 92.0.4515.131
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 92.0.902.67

! Doctor found issues in 1 category.
```

**Comment by yogithesymbian** [comment]
i have same issue [android device] , in iOS there is no problem. 
```
D/FileUtils( 4475): 	at android.app.ActivityThread.main(ActivityThread.java:7829)
D/FileUtils( 4475): 	at java.lang.reflect.Method.invoke(Native Method)
D/FileUtils( 4475): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
D/FileUtils( 4475): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:982)
D/FileUtils( 4475): Caused by: java.lang.IllegalStateException: java.io.IOException: stat failed: ENOENT (No such file or directory)
D/FileUtils( 4475): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2433)
D/FileUtils( 4475): 	at android.os.Parcel.createException(Parcel.java:2409)
D/FileUtils( 4475): 	at android.os.Parcel.readException(Parcel.java:2392)
D/FileUtils( 4475): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
D/FileUtils( 4475): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
D/FileUtils( 4475): 	at android.content.ContentProviderProxy.call(ContentProviderNative.java:732)
D/FileUtils( 4475): 	at android.content.ContentResolver.call(ContentResolver.java:2450)
D/FileUtils( 4475): 	at android.provider.MediaStore.getOriginalMediaFormatFileDescriptor(MediaStore.java:935)
D/FileUtils( 4475): 	... 20 more
I/flutter ( 4475): {debug puzzle_sound}Current player state: PlayerState.PLAYING
2
I/flutter ( 4475): _platformCallHandler call audio.onDuration {playerId: e0a634d0-7389-4f13-bff6-23912c4bacf0, value: 462}
I/flutter ( 4475): _platformCallHandler call audio.onCurrentPosition {playerId: e0a634d0-7389-4f13-bff6-23912c4bacf0, value: 0}
I/flutter ( 4475): _platformCallHandler call audio.onSeekComplete {playerId: e0a634d0-7389-4f13-bff6-23912c4bacf0, value: true}
I/flutter ( 4475): _platformCallHandler call audio.onDuration {playerId: e0a634d0-7389-4f13-bff6-23912c4bacf0, value: 462}
I/flutter ( 4475): _platformCallHandler call audio.onCurrentPosition {playerId: e0a634d0-7389-4f13-bff6-23912c4bacf0, value: 0}
I/flutter ( 4475): _platformCallHandler call audio.onDuration {playerId: e0a634d0-7389-4f13-bff6-23912c4bacf0, value: 462}
I/flutter ( 4475): _platformCallHandler call audio.onCurrentPosition {playerId: e0a634d0-7389-4f13-bff6-23912c4bacf0, value: 0}
I/flutter ( 4475): _platformCallHandler call audio.onComplete {playerId: e0a634d0-7389-4f13-bff6-23912c4bacf0, value: true}
I/flutter ( 4475): {debug puzzle_sound}Current player state: PlayerState.COMPLETED
I/flutter ( 4475): {debug puzzle_sound}sound completed
I/flutter ( 4475): {debug puzzle_sound}stop audio
I/flutter ( 4475): {debug puzzle_sound}Current player state: PlayerState.STOPPED
```

flutter doctor -v
```
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.5.2 20G95 darwin-arm, locale en-ID)
    • Flutter version 2.2.2 at /Users/yogiarifwidodo/dev/flutter
    • Framework revision d79295af24 (3 months ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/yogiarifwidodo/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/yogiarifwidodo/Library/Android/sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Zulu11.48+21-CA (build 11.0.11+9-LTS)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 12 (API 31) (emulator)
    • iPhone 12 Pro Max (mobile)  • 86E670B7-E3D7-428F-AD07-97488C68C4D0 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 93.0.4577.63

! Doctor found issues in 2 categories.
```

**Comment by yogithesymbian** [comment]
my alternative solution [https://stackoverflow.com/a/69139508/8122500](https://stackoverflow.com/a/69139508/8122500)

**Comment by jja08111** [comment]
I replaced the `play()` to `playBytes()` like below and It works without any errors.
```dart
player.playBytes(File(path).readAsBytesSync());
```

**Comment by Gustl22** [comment]
Can you recheck on `audioplayers: ^1.1.0` ?

**Comment by Gustl22** [comment]
Closing as stale.
